theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
collections:
    divisions_2020:
        output: true
        permalink: /2020/divisions/:name
    participants_2020:
        output: true
        permalink: /2020/participants/:name
    results_2020:
        output: true
        permalink: /2020/results/:name

    bibtex:
